# Generated by Django 2.2.16 on 2020-10-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
