# Generated by Django 2.2.19 on 2021-03-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_pictureuploadmodel_prof_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PictureUploadModel',
        ),
    ]
