# Generated by Django 2.2.19 on 2021-03-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0003_delete_pictureuploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUploadModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prof_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
