# Generated by Django 2.2.19 on 2021-03-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_pictureuploadmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PictureUploadModel',
            new_name='PictureUploadModel1',
        ),
    ]
