# Generated by Django 2.2.19 on 2021-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201017_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('contract', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=100)),
                ('phone_2', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('pic_name', models.CharField(max_length=100)),
                ('pic_contact', models.CharField(max_length=100)),
                ('pic_relation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLastID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
