# Generated by Django 2.2.19 on 2021-03-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210323_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
    ]
