# Generated by Django 2.2.19 on 2021-03-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('contract', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=100)),
                ('phone_2', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('pic_name', models.CharField(max_length=100)),
                ('pic_contact', models.CharField(max_length=100)),
                ('pic_relation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mst_employee',
                'managed': False,
            },
        ),
    ]
